site_name: Jam
site_url: https://jam.makridenko.ru
site_description: Simple and universal library for authorization.
copyright: Adrian Makridenko | <a href="https://github.com/mkrdnk/">@mkrdnk</a>

repo_name: mkrdnk/jam
repo_url: https://github.com/mkrdnk/jam
edit_uri: blob/release/docs/

nav:
  - Home: index.md
  - Getting started:
      - Installation: installation.md
      - Configuration: configuration.md
      - Quickstart: usage/quickstart.md
      - Core concepts:
          - Jam instance: usage/jam.md
          - Subjects: usage/subject.md
          - Authorization: usage/authz.md
  - Usage:
      - JOSE:
          - Overview: usage/jose/index.md
          - JWT: usage/jose/jwt.md
          - JWS: usage/jose/jws.md
          - JWE: usage/jose/jwe.md
          - JWK: usage/jose/jwk.md
          - Algorithms: usage/jose/algorithms.md
      - PASETO: usage/paseto.md
      - Server side sessions: usage/sessions.md
      - OAuth2: usage/oauth2.md
      - OTP: usage/otp.md
      - SAML: usage/saml.md
      - Logging: usage/logging.md
      - JSON serialization: usage/serializers.md
      - Testing: usage/test_client.md
      - Customization: usage/custom.md
      - CLI: usage/cli.md
      - Utils:
          - Keys generators: usage/utils/key_generators.md
          - Auth utils: usage/utils/auth_utils.md
  - Framework integration:
      - Litestar: framework_integrations/litestar.md
      - Starlette: framework_integrations/starlette.md
      - FastAPI: framework_integrations/fastapi.md
      - Flask: framework_integrations/flask.md
  - API Reference: api/SUMMARY.md
  - Breaking changes:
      - Deprecated: breaking_changes/deprecated.md
      - 3.0.0 -> 4.0.0: breaking_changes/jam300_to_400.md
      - 2.5.6 -> 3.0.0: breaking_changes/jam256_to_300.md
      - 1.1.4 -> 2.0.0: breaking_changes/jam114_to_200.md
  - Contributing: contributing.md
  - Changelog: https://github.com/mkrdnk/jam/blob/master/CHANGELOG.md
  - Philosophy: philosophy.md

theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.svg
  features:
    - navigation.instant
    - navigation.instant.progress
    - header.autohide
    - tabs
    - navigation.footer
  icon:
    repo: fontawesome/brands/github
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: pink
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/mkrdnk/jam
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/jamlib/

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
  - termynal:
      prompt_literal_start:
        - "$"
        - ">"
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            # show_doctring_examples: true
            merge_init_into_class: true
            show_source: false
            docstring_options:
              ignore_init_summary: true
            separate_signature: true
            show_root_heading: true
            show_root_full_path: false
            show_signature_annotations: true
            show_symbol_type_heading: true
            show_symbol_type_toc: true
            signature_crossrefs: true
            summary: true
  - gen-files:
      scripts:
        - docs/gen_api.py
  - literate-nav
